import type { ListingCard, PromoCard } from "./listings-data";

// Facts checked against the linked property or local tourism source on 2026-09-30.
// No live rates, star ratings, discounts or availability are implied by this directory.
export const hotelListings: ListingCard[] = [
  {
    id: "sapa-charm",
    name: "Sapa Charm Hotel",
    province: "Sa Pa · Lào Cai",
    image: "/images/services/hotel.webp",
    imageAlt: "Mặt tiền Sapa Charm Hotel với biển tên trên đường Mường Hoa",
    description: "Khách sạn trên đường Mường Hoa, hướng về núi Fansipan và thung lũng Mường Hoa.",
    sourceUrl: "https://sapacharm.com/about-us.html",
    priceUnit: "/ đêm",
  },
  {
    id: "coupole-sapa",
    name: "Hôtel de la Coupole – MGallery",
    province: "Sa Pa · Lào Cai",
    image: "/images/hotels/coupole-sapa-card.webp",
    imageAlt: "Mặt tiền vàng và mái vòm của Hôtel de la Coupole tại Sa Pa",
    description: "Khách sạn tại số 1 đường Hoàng Liên, trong trung tâm Sa Pa.",
    sourceUrl: "https://www.hoteldelacoupole.com/find-us/",
    priceUnit: "/ đêm",
  },
  {
    id: "nebula-moc-chau",
    name: "Nebula Glamping · Mộc Châu Island",
    province: "Mộc Châu · Sơn La",
    image: "/images/hotels/nebula-moc-chau-card.webp",
    imageAlt: "Các căn lưu trú mái vòm bạc của Nebula Glamping tại Mộc Châu Island",
    description: "Khu lưu trú mái vòm lấy cảm hứng từ hệ Mặt Trời, trong tổ hợp Mộc Châu Island.",
    sourceUrl: "https://mocchauisland.com/vi/stay",
    priceUnit: "/ đêm",
  },
  {
    id: "phadin-dien-bien",
    name: "Phadin Hotel · Nhà khách Quân khu II",
    province: "Điện Biên Phủ · Điện Biên",
    image: "/images/hotels/phadin-dien-bien-card.webp",
    imageAlt: "Mặt tiền Phadin Hotel, Nhà khách Quân khu 2 ở Điện Biên Phủ",
    description: "Cơ sở lưu trú tại Điện Biên Phủ, được ghi trong cơ sở dữ liệu ngành du lịch với tên Khách sạn Phadin.",
    sourceUrl: "https://csdl.vietnamtourism.gov.vn/cslt?page=820",
    priceUnit: "/ đêm",
  },
  {
    id: "mai-chau-ecolodge",
    name: "Mai Châu Ecolodge",
    province: "Mai Châu · Phú Thọ",
    image: "/images/hotels/mai-chau-ecolodge-card.webp",
    imageAlt: "Bể bơi ngoài trời với ô che lá và ghế nghỉ của Mai Châu Ecolodge, sau lưng là dãy núi",
    description: "Khu nghỉ tại Nà Chiềng, với các bungalow nhìn ra vườn, đồng lúa hoặc núi tùy hạng phòng.",
    sourceUrl: "https://maichau.ecolodge.asia/vi/index.html",
    priceUnit: "/ đêm",
  },
  {
    id: "mu-cang-chai-ecolodge",
    name: "Mù Cang Chải Ecolodge",
    province: "Mù Cang Chải · Lào Cai",
    image: "/images/destinations/mu-cang-chai-card.webp",
    imageAlt: "Ruộng bậc thang Mù Cang Chải, ảnh khu vực điểm đến",
    imageCaption: "Ảnh cảnh quan Mù Cang Chải",
    description: "Khu lưu trú ở Hua Khắt, với các ngôi nhà lấy cảm hứng từ nhà sàn Tây Bắc và vật liệu địa phương.",
    sourceUrl: "https://mucangchaiecolodge.com/khu-nghi-duong/",
    priceUnit: "/ đêm",
  },
  {
    id: "la-beaute-bac-ha",
    name: "La Beauté Bắc Hà",
    province: "Bắc Hà · Lào Cai",
    image: "/images/destinations/bac-ha-card.webp",
    imageAlt: "Chợ Bắc Hà, ảnh sinh hoạt tại khu vực điểm đến",
    imageCaption: "Ảnh khu vực: chợ Bắc Hà",
    description: "Homestay tại làng du lịch cộng đồng Na Lo, được giới thiệu trên cổng thông tin du lịch Bắc Hà.",
    sourceUrl: "https://www.bachatourism.com/danh-muc-cam-nang-du-lich/luu-tru/",
    priceUnit: "/ đêm",
  },
  {
    id: "panhou-retreat",
    name: "Panhou Retreat",
    province: "Hoàng Su Phì · Tuyên Quang",
    image: "/images/hotels/panhou-retreat-card.webp",
    imageAlt: "Các bungalow mái lá của Panhou Retreat nằm giữa vườn cây xanh nhìn từ trên cao",
    description: "Khu nghỉ tại Làng Giang, Thông Nguyên; các bungalow dùng tre, gỗ và đá, nằm giữa không gian vườn.",
    sourceUrl: "https://www.panhouretreat.com/vi/trang-chu",
    priceUnit: "/ đêm",
  },
];

export const hotelPromos: PromoCard[] = hotelListings.map((hotel) => ({
  id: `stay-${hotel.id}`,
  name: hotel.name,
  province: hotel.province,
  image: hotel.image,
  imageAlt: hotel.imageAlt,
  imageCaption: hotel.imageCaption,
  description: hotel.description,
  sourceUrl: hotel.sourceUrl,
  unit: hotel.priceUnit,
}));

export const hotelPhotoCredits = [
  {
    key: "sapa-charm",
    name: "Sapa Charm Hotel",
    author: "Andre Hospers",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sapa_Charm_hotel_Vietnam.jpg",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
  },
  {
    key: "coupole",
    name: "Hôtel de la Coupole – MGallery",
    author: "Kirandeep Singh Walia",
    sourceUrl: "https://www.pexels.com/photo/grand-architecture-of-sa-pa-hotel-with-blue-sky-34389395/",
    license: "Pexels License",
    licenseUrl: "https://www.pexels.com/license/",
  },
  {
    key: "nebula",
    name: "Nebula Glamping · Mộc Châu Island",
    author: "Quang Nguyen Vinh",
    sourceUrl: "https://www.pexels.com/photo/silver-domes-at-moc-chau-island-mountain-park-and-resort-in-vietnam-26729596/",
    license: "Pexels License",
    licenseUrl: "https://www.pexels.com/license/",
  },
  {
    key: "phadin",
    name: "Phadin Hotel · Nhà khách Quân khu II",
    author: "Ioe2015",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Phadin_Hotel_%E2%80%93_Qu%C3%A2n_khu_2.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
  },
  {
    key: "panhou",
    name: "Panhou Retreat",
    author: "Travelsenseasia",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Panhou-retreat-1-9812-1720599832.jpg",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
  },
  {
    key: "mai-chau-ecolodge",
    name: "Mai Châu Ecolodge",
    author: "PANGEA Travel",
    sourceUrl: "https://www.flickr.com/photos/8541815@N07/28533225215",
    license: "CC BY-NC-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-nc-sa/2.0/",
  },
];
